### ISSUE TITLE
Needed Modbus Registers 

### ISSUE THREAD

**Issue by patrickfe** [maga-1/mqtt2vitocal#1]
Hey,
first of all, thank you for this nice project! I had basically a quite similar idea, emulating an Viessmann energy meters with an esp32 and controll it via mttq. However, the delivery of the heat pump has been delayed and I have not yet had the opportunity to implement this.

I'm trying to understand the code, but I'm not really familiar with Modbus and I don't get it. As far as I know, the Viesmann meter is a Saia ALE3D5FD10C3A00 and if this meter is emulated, then the required registers should be found in the data sheet (http://datenblatt.stark-elektronik.de/SBC/26-527_GER_DS_EnergyMeter-ALE3-with-Modbus.pdf). But somehow I can't map that properly to the datasheet. Could you describe this part with the required registers and addresses maybe a bit more detailed?

Have you already gained some experience in the field? How well does the heat pump adapt to the remaining power? :) 

Thank you very much!

**Comment by maga-1** [comment]
Hi,

without a heatpump connected you will not see the registers it is reading. Once connected you will see the addresses in the log.

My 200-S reads the following addresses:
1, 22, 25, 38, 43, 48, and 28-35

Looking at your data sheet, most of them make sense. The imporant ones are 38, 43, and 48, they carry the current power per phase. Since the heatpump does not know which phase(es) it is connected to, the individual values are not relevant, only the sum. I don't know if register 1 (Firmware version) has any impact on the behaviour, I leave it at 0. 22 and 25 definitely should be 0 since they contain error codes. 28-35 is metering stuff which I did not bother to implement. I believe this is only for statistics, but I don't want to read my pv statistics on the display of my heatpump anyway (although it seems to work even when sending always 0).

So basically, we have to care for registers 38, 43, and 48.

I think, the implementation of pymodbus is really good, since it implements a real set of registers. This code fragment initalizes 100 registers starting at address 0 with 0 values:

```python
 store = ModbusSlaveContext(
        di=ModbusSequentialDataBlock(0, [0]*100),
        co=ModbusSequentialDataBlock(0, [0]*100),
        hr=ThreadSafeDataBlock(ModbusSequentialDataBlock(0, [0]*100)),
        ir=ModbusSequentialDataBlock(0, [0]*100))
```
Please note, addresses are shifted one position compared to the data sheet, e.g. 38 becomes 37. After initalization the program returns 0 to all requests for addresses 0 to 100.
In the `on_message` method a new power value from mqtt is handled. It is devided by 30 (see multipliers in data sheet) and stored to the registers in following code:

```python
   register = 3
    slave_id = 60
    addresses = [37, 42, 47]
    for address in addresses:
        context[slave_id].setValues(register, address, payload)
```

All subsequent requests will return proper values, which can be verified in the heatpump's display.


My experiences with this setup are mixed, but our pv sytem was installed only end of September 2022. In my opinion, heating works quite well. With excess solar power, the heatpump rises the target room temperature while adopting to available power. However, with hot water I did not get the temperature rise to work yet. I expected the pump to run on lower levels for a longer time and rise the target temperature, but it always consumes around 3kW. Currently, we do not have that amount of excess power, so perhaps it works as designed. I will see in the summer. Another possible explanation is our hot water container with 300 l capacity. We never have to charge it more than once a day, so perhaps the heatpump sees no point in rising the teamperature. Or its software has a bug. I will experiment some more with its settings in spring. If it still does not work, I am going to automatically reprogram the target temperature depending on the solar forecast using the Viessman web api.

I hope, this gives you some insights. If you have further questions, feel free to ask.

**Comment by patrickfe** [comment]
Thank you so much for the detailed explanation!
 
Apparently I was misled by the term Address and Register "R" in the data sheet. However, now everything is clear to me and I can transfer it to the ESP32 if necessary or I stay with your approach. 

I hope that the approach with the meter emulation is perhaps a bit more advanced and adapts better to the available energy,  compared to the binary "smart grid" function or reprogramming of the target temperature. It will be another 2-3 weeks before our heat pump starts its operation, but I am already excited to test it. :) 


Thanks again!
